// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtyX4oB3RRRhMieewLZ2FT-e9wmmdnSpo',
    appId: '1:690205440828:web:b5c8e8c7432ed698febc39',
    messagingSenderId: '690205440828',
    projectId: 'activityplan-22963',
    authDomain: 'activityplan-22963.firebaseapp.com',
    storageBucket: 'activityplan-22963.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOwPgV5-v2RIYNkJLHRn6ZKUoKeYqZ7DM',
    appId: '1:690205440828:android:0dd64d582c10105ffebc39',
    messagingSenderId: '690205440828',
    projectId: 'activityplan-22963',
    storageBucket: 'activityplan-22963.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOCsDM5KoQoNSFwSH6YlccR-WINAJkSaU',
    appId: '1:690205440828:ios:51ce5b05adfb6b9afebc39',
    messagingSenderId: '690205440828',
    projectId: 'activityplan-22963',
    storageBucket: 'activityplan-22963.appspot.com',
    iosBundleId: 'com.example.activityApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOCsDM5KoQoNSFwSH6YlccR-WINAJkSaU',
    appId: '1:690205440828:ios:41206d97783ad68cfebc39',
    messagingSenderId: '690205440828',
    projectId: 'activityplan-22963',
    storageBucket: 'activityplan-22963.appspot.com',
    iosBundleId: 'com.example.activityApp.RunnerTests',
  );
}
